prdc_lzw::LzwNode Class Reference
LZW辞書のノード
#include <Dictionary.h>
Public Member Functions
int getData ()
LzwNode * FindChild (char c)
文字cを子供に持っていればそれを返す
Private Member Functions
LzwNode ()
LzwNode (int d, char c)
virtual ~LzwNode ()
void InsertChild (int data, char c)
子ノードの挿入
Private Attributes
int data
char content
辞書番号
std::vector< LzwNode * > children
格納文字
Friends
class Dictionary
Detailed Description
LZW辞書のノード
内部に辞書番号（辞書に何個目に追加されたか）と単語(検索用)を持つ
Definition at line 22 of file Dictionary.h.
Constructor & Destructor Documentation
prdc_lzw::LzwNode::LzwNode () [private]
Definition at line 13 of file Dictionary.cpp.
Referenced by InsertChild().
prdc_lzw::LzwNode::LzwNode (int d, char c) [private]
Definition at line 16 of file Dictionary.cpp.
prdc_lzw::LzwNode::~LzwNode () [private], [virtual]
Definition at line 20 of file Dictionary.cpp.
References children.
Member Function Documentation
LzwNode * prdc_lzw::LzwNode::FindChild (char c)
文字cを子供に持っていればそれを返す
Parameters
c 探索したい文字
Returns
存在すればノードのポインタ、なければNULL
Definition at line 26 of file Dictionary.cpp.
References children, and content.
Referenced by prdc_lzw::compress().
int prdc_lzw::LzwNode::getData () [inline]
Definition at line 25 of file Dictionary.h.
References data.
Referenced by prdc_lzw::compress().
void prdc_lzw::LzwNode::InsertChild (int data, char c) [private]
子ノードの挿入
Attention
辞書クラスからのみ呼び出される
(外部から直接子ノードを挿入させない)
Parameters
data 辞書番号
c 格納文字
Definition at line 36 of file Dictionary.cpp.
References children, and LzwNode().
Referenced by prdc_lzw::Dictionary::AddNode().
Friends And Related Function Documentation
friend class Dictionary [friend]
Definition at line 23 of file Dictionary.h.
Member Data Documentation
std::vector<LzwNode*> prdc_lzw::LzwNode::children [private]
格納文字
Definition at line 51 of file Dictionary.h.
Referenced by prdc_lzw::Dictionary::Dictionary(), FindChild(), InsertChild(), and ~LzwNode().
char prdc_lzw::LzwNode::content [private]
辞書番号
Definition at line 50 of file Dictionary.h.
Referenced by FindChild().
int prdc_lzw::LzwNode::data [private]
Definition at line 49 of file Dictionary.h.
Referenced by getData().
The documentation for this class was generated from the following files:
src/Dictionary.h
src/Dictionary.cpp