prdc_lzw::Dictionary Class Reference
LZW辞書クラス
#include <Dictionary.h>
Public Member Functions
Dictionary ()
Dictionary (std::string uncompress, unsigned int max_dicsize=default_max_dicsize, unsigned int max_length=default_max_length)
virtual ~Dictionary ()
LzwNode * get_root ()
void AddNode (LzwNode *node, char key_word)
辞書中の指定したノードに文字を追加する
LzwNode * SearchNode (std::string key_word)
key_wordのノードを辞書から検索し返す。
std::vector< int > & Compress (const std::string &uncompressed)
文字列を圧縮し、辞書を抽出する
Public Attributes
unsigned int max_dicsize
辞書に登録できる単語の数
unsigned int max_length
辞書に登録できる単語の長さの上限
std::vector< std::string > binding
文字と辞書番号を関連付ける配列
std::vector< int > compressed
圧縮後の辞書番号配列
std::vector< std::pair
*
< std::string, double > > histgram
圧縮後文字列中にそれぞれの単語が何回存在するか(全て足すと１になるように正規化)
Private Attributes
int dict_size
辞書に単語がいくつ登録されているか(辞書番号をつける際に利用)
std::unique_ptr< LzwNode > root
ルートノード
Detailed Description
LZW辞書クラス
文字列の登録と検索ができる
Author
uchino
Definition at line 73 of file Dictionary.h.
Constructor & Destructor Documentation
prdc_lzw::Dictionary::Dictionary ()
Definition at line 49 of file Dictionary.cpp.
References binding, and root.
prdc_lzw::Dictionary::Dictionary (std::string uncompress, unsigned int max_dicsize = default_max_dicsize, unsigned int max_length = default_max_length)
Definition at line 59 of file Dictionary.cpp.
References binding, Compress(), and root.
prdc_lzw::Dictionary::~Dictionary () [virtual]
Definition at line 113 of file Dictionary.cpp.
Member Function Documentation
void prdc_lzw::Dictionary::AddNode (LzwNode * node, char key_word)
辞書中の指定したノードに文字を追加する
Parameters
key_word 追加する文字
node 文字を追加するノード
Note
辞書番号の管理のため直接ノードに子を追加させない
Definition at line 116 of file Dictionary.cpp.
References dict_size, and prdc_lzw::LzwNode::InsertChild().
Referenced by Compress(), and prdc_util::Compress().
std::vector< int > & prdc_lzw::Dictionary::Compress (const std::string & uncompressed)
文字列を圧縮し、辞書を抽出する
Parameters
uncompressed 圧縮する文字列
Definition at line 72 of file Dictionary.cpp.
References AddNode(), binding, compressed, prdc_lzw::LzwNode::FindChild(), prdc_lzw::LzwNode::get_data(), get_root(), max_dicsize, max_length, and root.
Referenced by Dictionary(), and main().
LzwNode* prdc_lzw::Dictionary::get_root () [inline]
Definition at line 80 of file Dictionary.h.
References root.
Referenced by Compress(), and prdc_util::Compress().
LzwNode * prdc_lzw::Dictionary::SearchNode (std::string key_word)
key_wordのノードを辞書から検索し返す。
Parameters
key_word 検索する文字列
Returns
key_wordのノード。辞書中に存在しなければNULLを返す
Definition at line 121 of file Dictionary.cpp.
References prdc_lzw::LzwNode::FindChild(), and root.
Member Data Documentation
std::vector<std::string> prdc_lzw::Dictionary::binding
文字と辞書番号を関連付ける配列
Definition at line 90 of file Dictionary.h.
Referenced by Compress(), prdc_util::Compress(), Dictionary(), and prdc_util::MakeHistgram().
std::vector<int> prdc_lzw::Dictionary::compressed
圧縮後の辞書番号配列
Definition at line 92 of file Dictionary.h.
Referenced by Compress(), and prdc_util::MakeHistgram().
int prdc_lzw::Dictionary::dict_size [private]
辞書に単語がいくつ登録されているか(辞書番号をつける際に利用)
Definition at line 117 of file Dictionary.h.
Referenced by AddNode().
std::vector<std::pair<std::string, double> > prdc_lzw::Dictionary::histgram
圧縮後文字列中にそれぞれの単語が何回存在するか(全て足すと１になるように正規化)
Definition at line 94 of file Dictionary.h.
Referenced by main(), prdc_util::MakeHistgram(), prdc_util::NormalizedDictionaryDistance(), and prdc_util::NormalizedMultisetDistance().
unsigned int prdc_lzw::Dictionary::max_dicsize
辞書に登録できる単語の数
Definition at line 85 of file Dictionary.h.
Referenced by Compress(), and prdc_util::Compress().
unsigned int prdc_lzw::Dictionary::max_length
辞書に登録できる単語の長さの上限
Definition at line 87 of file Dictionary.h.
Referenced by Compress(), and prdc_util::Compress().
std::unique_ptr<LzwNode> prdc_lzw::Dictionary::root [private]
ルートノード
Definition at line 120 of file Dictionary.h.
Referenced by Compress(), Dictionary(), get_root(), and SearchNode().
The documentation for this class was generated from the following files:
src/Dictionary.h
src/Dictionary.cpp