prdc_lzw Namespace Reference
PRDCで用いるLZW圧縮に関する名前空間
Classes
class LzwNode
LZW辞書のノード
class Dictionary
LZW辞書クラス
Functions
void compress (const std::string &uncompressed, std::vector< int > &compressed, Dictionary &output_dic)
文字列を圧縮し、辞書を抽出する
Detailed Description
PRDCで用いるLZW圧縮に関する名前空間
Function Documentation
void prdc_lzw::compress (const std::string & uncompressed, std::vector< int > & compressed, Dictionary & output_dic)
文字列を圧縮し、辞書を抽出する
Parameters
uncompressed 圧縮する文字列
compressed 圧縮された文字列（数値）
output_dic 出力される辞書
Definition at line 14 of file Lzw.cpp.
References prdc_lzw::Dictionary::AddNodes(), prdc_lzw::LzwNode::data, prdc_lzw::Dictionary::IsExist(), and prdc_lzw::Dictionary::SearchNord().
Referenced by main().